config/routes.rb
Nja::Application.routes.draw do
  resources :challenges
  resources :members

  root :to => 'home#index'

  match '/leaderboard' => "home#leaderboard", :as => :leaderboard
  match '/store' => "home#store", :as => :store

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  attr_accessible :description, :level, :name, :points, :steps, :ctype, :image
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :member_id, :name, :points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
    @main_body_class = "challenges"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @challenges }
    end
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    @challenge = Challenge.find(params[:id])
    @main_body_class = "challenge"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @challenge }
    end
  end

  # GET /challenges/new
  # GET /challenges/new.json
  def new
    @challenge = Challenge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @challenge }
    end
  end

  # GET /challenges/1/edit
  def edit
    @challenge = Challenge.find(params[:id])
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(params[:challenge])

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render json: @challenge, status: :created, location: @challenge }
      else
        format.html { render action: "new" }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /challenges/1
  # PUT /challenges/1.json
  def update
    @challenge = Challenge.find(params[:id])

    respond_to do |format|
      if @challenge.update_attributes(params[:challenge])
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy

    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def store
  @main_body_class = "store"
end


end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @main_body_class = "profile"
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/challenges/_form.html.erb
<%= form_for @challenge, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', :rows=>2 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ctype, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ctype, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :steps, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :steps, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :level, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :level, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :points, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :points, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                challenges_path, :class => 'btn' %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<%- model_class = Challenge -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/challenges/index.html.erb
<%- model_class = Challenge -%>

<div class="swiper-container swiper-partial">
  <div class="swiper-wrapper">
    <% @challenges.each do |challenge| %>
        <div class="swiper-slide blue-slide">
	  <div class="card-action">
	    <div class="points">
	      <%= pluralize(challenge.points, 'point') %>
	    </div>
	    <div class="friends">
	      <%= link_to image_tag('friends.png'), challenge %>
  	    </div>
	    <div class="title">
  	      <%= challenge.name %>
	    </div>
	    <%= image_tag challenge.image.blank? ? 'pushup.png' : challenge.image %>
  	    <%= link_to "Accept Challenge", challenges_path, :class => 'my-btn' %>
	  </div>
        </div>
    <% end %>
  </div>
</div>


<script>
$(function(){
	var mySwiper = $('.swiper-container').swiper({
		//Your options here:
		mode:'horizontal',
		loop: true
		//etc..
	});
})
</script>

app/views/challenges/new.html.erb
<%- model_class = Challenge -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/challenges/show.html.erb
<%- model_class = Challenge -%>
<div class="challenge-title">
  <p class="mini"><%= @challenge.description.upcase %></p>
</div>

<div class="challenge-header challengers">
  <%= image_tag 'friends.png', :class=>"header-img" %>
  <p>10 OF YOUR FRIENDS TOOK THIS CHALLENGE</p>

  <div class="people">
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
  </div>
</div>

<div class="challenge-header finishers">
  <%= image_tag 'friends.png', :class=>"header-img" %>
  <p>3 OF YOUR FRIENDS COMPLETED THIS CHALLENGE</p>

  <div class="people">
    <div class="person">
    </div>
    <div class="person">
    </div>
    <div class="person">
    </div>
  </div>
</div>

app/views/home/leaderboard.html.erb
<div class="page-header">
  <h1>Leaderboard</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NJA</title>

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="<%= @main_body_class ? @main_body_class : 'main' %>">
      <div class="nav-container">
        <div class="overlay" id="overlay" style="display:none;"></div>
        <div class="nav-slider" id="nav-slider">
	  <div class="nav-items">
	    <li><%= link_to Member.first.name, Member.first %>
		<%= link_to image_tag("member.png", :class=>"profile-logo"), Member.first %></li>
 	    <span class="nav-divider"></span>
	    <li><%= link_to "Challenges", challenges_path %></li>
 	    <span class="nav-divider"></span>
	    <li><%= link_to "Leaderboard", leaderboard_path %></li>
 	    <span class="nav-divider"></span>
	    <li><%= link_to "Store", store_path %>
		<span class="pull-right">560 Points</span>
	    </li>
	  </div>
	  <div class="bar">
	    <div id="ninja">
              <a href="#"><%= image_tag('dropdown.png', :size => "30x30") %></a>	
	    </div>
	  </div>
        </div>
      </div>
            <%= link_to '<div class="hidden list-icon">
                <span class="list-bar"></span>
                <span class="list-bar"></span>
                <span class="list-bar"></span>
                <span class="list-bar"></span>
            </div>'.html_safe, challenges_path %>

<div class="container">
  <div class="row">
    <div class="span9">
	<%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :member_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :member_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :points, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :points, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn' %>
  </div>
<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:member_id) %></th>
      <th><%= model_class.human_attribute_name(:points) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.id, member_path(member) %></td>
        <td><%= member.name %></td>
        <td><%= member.member_id %></td>
        <td><%= member.points %></td>
        <td><%=l member.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>